"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useLaunch } from "@/lib/context/LaunchContext";
import { findContentItem } from "@/lib/launch-plan";
import { AppHeader } from "@/components/shared/AppHeader";
import { Breadcrumb } from "@/components/shared/Breadcrumb";
import { ImproveWithAIPanel } from "@/components/launch-plan/ImproveWithAIPanel";
import type { TaskGroupContentItem } from "@/lib/types";

function ContentItemDetailContent({
  launchId,
  groupId,
  itemId,
  launch,
  group,
  item,
}: {
  launchId: string;
  groupId: string;
  itemId: string;
  launch: { id: string; name?: string };
  group: { title: string; connectedSystem?: string; owner?: string };
  item: TaskGroupContentItem;
}) {
  const router = useRouter();
  const { updateItemContent, updateItemStatus } = useLaunch();
  const initialContent = typeof item.content === "string" ? item.content : "";
  const [content, setContent] = useState(initialContent);
  const [showAIPanel, setShowAIPanel] = useState(false);

  useEffect(() => {
    if (typeof item.content === "string") setContent(item.content);
  }, [item.id, item.content]);

  const breadcrumb = [
    { label: "Dashboard", href: "/" },
    { label: String(launch?.name ?? "Launch"), href: `/launch/${launchId}` },
    { label: String(group?.title ?? "Task"), href: `/launch/${launchId}` },
    { label: String(item?.title ?? "Content") },
  ];

  function handleApplySuggestion(text: string) {
    setContent((prev) => prev + "\n\n" + text);
    setShowAIPanel(false);
  }

  function handleSubmitAndMarkDone() {
    updateItemContent(launchId, groupId, itemId, content);
    updateItemStatus(launchId, groupId, itemId, "done");
    router.push(`/launch/${launchId}`);
  }

  function handleSaveChanges() {
    updateItemContent(launchId, groupId, itemId, content);
  }

  const isDone = item.status === "done";

  return (
    <div className="min-h-screen bg-gray-50">
      <AppHeader />
      <ImproveWithAIPanel
        isOpen={showAIPanel}
        onClose={() => setShowAIPanel(false)}
        currentContent={content}
        onApplySuggestion={handleApplySuggestion}
      />
      <main className="mx-auto max-w-3xl px-4 py-8 sm:px-6">
        <Breadcrumb items={breadcrumb} />
        <div className="mt-3 rounded-lg border border-gray-200 bg-white shadow-sm">
          <div className="border-b border-gray-200 px-4 py-3">
            <div className="flex flex-wrap items-center gap-2">
              <h1 className="text-lg font-semibold text-gray-900">
                {String(item.title ?? "Content")}
              </h1>
              <span className="rounded bg-gray-100 px-2 py-0.5 text-xs text-gray-600">
                {String(group?.title ?? "")}
              </span>
              <span className="rounded bg-gray-100 px-2 py-0.5 text-xs text-gray-600">
                Generated by Launch AI
              </span>
              {group?.connectedSystem && group.connectedSystem !== "None" && (
                <span className="rounded border border-gray-200 bg-gray-50 px-2 py-0.5 text-xs text-gray-600">
                  {String(group.connectedSystem)}
                </span>
              )}
              <span className="text-xs text-gray-400">{String(group?.owner ?? "")}</span>
            </div>
          </div>
          <div className="p-4">
            <label htmlFor="task-content" className="sr-only">
              Content
            </label>
            <textarea
              id="task-content"
              value={content ?? ""}
              onChange={(e) => setContent(e.target.value)}
              rows={12}
              className="block w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
              placeholder="AI-generated content for this item..."
            />
          </div>
          <div className="flex flex-wrap items-center gap-2 border-t border-gray-200 px-4 py-3">
            <button
              type="button"
              onClick={() => setShowAIPanel(true)}
              className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
            >
              Improve with AI
            </button>
            {isDone ? (
              <button
                type="button"
                onClick={handleSaveChanges}
                className="rounded-lg bg-blue-600 px-3 py-2 text-sm font-medium text-white hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
              >
                Save changes
              </button>
            ) : (
              <button
                type="button"
                onClick={handleSubmitAndMarkDone}
                className="rounded-lg bg-blue-600 px-3 py-2 text-sm font-medium text-white hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
              >
                Submit & mark done
              </button>
            )}
            <button
              type="button"
              disabled
              title="Coming soon"
              className="cursor-not-allowed rounded-lg border border-gray-200 bg-gray-100 px-3 py-2 text-sm font-medium text-gray-400"
            >
              Export / Send
            </button>
          </div>
        </div>
        <p className="mt-4 text-sm text-gray-500">
          Edit the content above, use Improve with AI to refine it, then Submit & mark done to
          save and complete this item on the launch plan.
        </p>
      </main>
    </div>
  );
}

export function TaskDetailClient({ launchId, itemId }: { launchId: string; itemId: string }) {
  const { getLaunchById } = useLaunch();
  const launch = getLaunchById(launchId);
  const found = findContentItem(launch ?? null, itemId);

  if (!launch) {
    return (
      <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center px-4">
        <p className="text-gray-600">Launch not found.</p>
        <Link href="/" className="mt-4 text-blue-600 hover:underline">
          Dashboard
        </Link>
      </div>
    );
  }

  if (!found) {
    return (
      <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center px-4">
        <p className="text-gray-600">Content item not found.</p>
        <Link href={`/launch/${launchId}`} className="mt-4 text-blue-600 hover:underline">
          Back to launch plan
        </Link>
      </div>
    );
  }

  const { group, item } = found;

  return (
    <ContentItemDetailContent
      launchId={launchId}
      groupId={group.id}
      itemId={itemId}
      launch={launch}
      group={group}
      item={item}
    />
  );
}
