import Link from "next/link";
import type { Launch, FeatureSize } from "@/lib/types";

interface LaunchPlanHeaderProps {
  launch: Launch;
  progress: { done: number; total: number; pct: number };
  canMarkReady: boolean;
  onMarkReady: () => void;
}

function getSizeBadgeClass(size: FeatureSize): string {
  switch (size) {
    case "minor":
      return "bg-blue-100 text-blue-800";
    case "medium":
      return "bg-orange-100 text-orange-800";
    case "major":
      return "bg-red-100 text-red-800";
    default:
      return "bg-gray-100 text-gray-800";
  }
}

export function LaunchPlanHeader({
  launch,
  progress,
  canMarkReady,
  onMarkReady,
}: LaunchPlanHeaderProps) {
  const sizeClass = getSizeBadgeClass(launch.featureSize);

  return (
    <div className="mb-8">
      <div className="flex flex-wrap items-center gap-2 text-sm text-gray-500">
        <span
          className={`rounded-full px-2.5 py-0.5 font-medium ${sizeClass}`}
        >
          {launch.featureSize.charAt(0).toUpperCase() + launch.featureSize.slice(1)}
        </span>
        <span>Target: {launch.targetDate}</span>
        <span className="text-gray-400">·</span>
        <span className="rounded bg-gray-100 px-2 py-0.5 text-gray-600">
          Generated by Launch AI
        </span>
      </div>
      <h1 className="mt-2 text-2xl font-bold text-gray-900">{launch.name}</h1>
      <div className="mt-4 rounded-lg border border-gray-200 bg-gray-50 p-4">
        <p className="text-sm text-gray-700">{launch.plan.scopeSummary}</p>
      </div>
      <div className="mt-4 flex flex-wrap items-center gap-3">
        <Link
          href={`/launch/${launch.id}/assets`}
          className="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
        >
          View Assets
        </Link>
        <button
          type="button"
          onClick={onMarkReady}
          disabled={!canMarkReady}
          className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
        >
          Mark Ready
        </button>
      </div>
      <div className="mt-6">
        <div className="flex items-center justify-between text-sm">
          <span className="font-medium text-gray-700">
            {progress.done} of {progress.total} items complete
          </span>
          <span className="text-gray-500">{progress.pct}%</span>
        </div>
        <div className="mt-1.5 h-2 w-full overflow-hidden rounded-full bg-gray-200">
          <div
            className="h-full rounded-full bg-blue-600 transition-all"
            style={{ width: `${progress.pct}%` }}
          />
        </div>
      </div>
    </div>
  );
}
