"use client";

import { useState, useEffect } from "react";
import type { Asset } from "@/lib/types";

interface AssetSectionProps {
  asset: Asset;
  onContentChange: (content: string) => void;
}

export function AssetSection({ asset, onContentChange }: AssetSectionProps) {
  const [content, setContent] = useState(asset.content);
  const [isEditing, setIsEditing] = useState(false);

  useEffect(() => {
    setContent(asset.content);
  }, [asset.id, asset.content]);

  function handleBlur() {
    setIsEditing(false);
    if (content !== asset.content) {
      onContentChange(content);
    }
  }

  const title =
    asset.type === "release_notes"
      ? "Release Notes"
      : asset.type === "sales_email"
        ? "Sales Email"
        : "In-App Copy";

  return (
    <div className="rounded-lg border border-gray-200 bg-white shadow-sm">
      <div className="flex items-center justify-between border-b border-gray-200 px-4 py-3">
        <div className="flex items-center gap-2">
          <h2 className="text-lg font-semibold text-gray-900">{title}</h2>
          <span className="rounded bg-gray-100 px-2 py-0.5 text-xs text-gray-600">
            Generated by Launch AI
          </span>
          <span className="text-xs text-gray-400">Draft v1</span>
        </div>
        <button
          type="button"
          onClick={() => setIsEditing(!isEditing)}
          className="rounded border border-gray-300 bg-white px-3 py-1.5 text-sm font-medium text-gray-700 hover:bg-gray-50"
        >
          {isEditing ? "Preview" : "Edit"}
        </button>
      </div>
      <div className="p-4">
        {isEditing ? (
          <textarea
            value={content}
            onChange={(e) => setContent(e.target.value)}
            onBlur={handleBlur}
            rows={12}
            className="block w-full rounded-md border border-gray-300 px-3 py-2 font-mono text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
            placeholder="Content..."
          />
        ) : (
          <div className="whitespace-pre-wrap rounded-md border border-gray-100 bg-gray-50 p-4 font-mono text-sm text-gray-800">
            {content}
          </div>
        )}
      </div>
      <div className="flex flex-wrap gap-2 border-t border-gray-200 px-4 py-3">
        <button
          type="button"
          disabled
          title="Coming soon"
          className="cursor-not-allowed rounded-lg border border-gray-200 bg-gray-100 px-3 py-2 text-sm font-medium text-gray-400"
        >
          Push to Salesforce
        </button>
        <button
          type="button"
          disabled
          title="Coming soon"
          className="cursor-not-allowed rounded-lg border border-gray-200 bg-gray-100 px-3 py-2 text-sm font-medium text-gray-400"
        >
          Publish to Help Center
        </button>
        <button
          type="button"
          disabled
          title="Coming soon"
          className="cursor-not-allowed rounded-lg border border-gray-200 bg-gray-100 px-3 py-2 text-sm font-medium text-gray-400"
        >
          Export to Pendo
        </button>
      </div>
    </div>
  );
}
